/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/barn.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Barn(props) {
  const { nodes, materials } = useGLTF('/models/barn.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Barn_001.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('/models/barn.gltf')
