/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/drone.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Drone(props) {
  const { nodes, materials } = useGLTF('/models/drone.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[2.132, 0.067, -2.073]} />
      <mesh geometry={nodes.prop1.geometry} material={nodes.prop1.material} position={[2.131, 0, -2.096]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-2.164, 0.067, -2.073]} />
      <mesh geometry={nodes.prop2.geometry} material={nodes.prop2.material} position={[-2.165, 0, -2.096]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-1.928, 0.067, 1.953]} />
      <mesh geometry={nodes.prop3.geometry} material={nodes.prop3.material} position={[-1.928, 0, 1.929]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[1.996, 0.067, 1.953]} />
      <mesh geometry={nodes.prop4.geometry} material={nodes.prop4.material} position={[1.996, 0, 1.929]} />
    </group>
  )
}

useGLTF.preload('/models/drone.glb')
