/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/drone2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useLoader } from '@react-three/fiber'
import * as THREE from 'three'

export function Drone(props) {
  const { nodes, materials } = useGLTF('/models/drone.glb')

  const texture = useLoader(THREE.TextureLoader, '/images/drone-matcap.png')

  const motor1 = useRef()
  const motor2 = useRef()
  const motor3 = useRef()
  const motor4 = useRef()

  const material = new THREE.MeshMatcapMaterial({map: texture})
  const material2 = new THREE.MeshStandardMaterial({color:"#444444", roughness: 0.4, metalness: 0.5})



  useFrame((state, delta) => {
    console.log(motor1.current)
    motor1.current.rotation.y += delta * 10
    motor2.current.rotation.y -= delta * 10
    motor3.current.rotation.y += delta * 10
    motor4.current.rotation.y -= delta * 10
  })


  return (
    <group rotation-y={Math.PI / 2} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={material} scale={[0.859, 0.163, 0.859]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={material} position={[0, 0.013, 0]} scale={[1.481, 0.267, 1.481]} />
      <mesh geometry={nodes.motor1.geometry} material={material} position={[2.559, 0, -2.576]} scale={[0.351, 0.175, 0.351]} />
      <mesh ref={motor1} geometry={nodes.Cube.geometry} material={material2} position={[2.576, 0.51, -2.576]} scale={[0.221, 0.051, 1.497]} />
      <mesh geometry={nodes.Sphere.geometry} material={material2} position={[0.153, -1.396, 0]} scale={0.62} />
      <mesh  geometry={nodes.Cube001.geometry} material={material2} position={[0, -0.211, 0]} scale={0.346} />
      <mesh  geometry={nodes.motor1001.geometry} material={material} position={[2.559, 0, 2.509]} scale={[0.351, 0.175, 0.351]} />
      <mesh ref={motor3} geometry={nodes.Cube002.geometry} material={material2} position={[2.576, 0.51, 2.51]} scale={[0.221, 0.051, 1.497]} />
      <mesh  geometry={nodes.motor1002.geometry} material={material} position={[-2.584, 0, 2.509]} scale={[0.351, 0.175, 0.351]} />
      <mesh ref={motor4} geometry={nodes.Cube003.geometry} material={material2} position={[-2.567, 0.51, 2.51]} scale={[0.221, 0.051, 1.497]} />
      <mesh  geometry={nodes.motor1003.geometry} material={material} position={[-2.584, 0, -2.533]} scale={[0.351, 0.175, 0.351]} />
      <mesh ref={motor2} geometry={nodes.Cube004.geometry} material={material2} position={[-2.567, 0.51, -2.533]} scale={[0.221, 0.051, 1.497]} />
    </group>
  )
}

useGLTF.preload('/models/drone.glb')
