/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/helo.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Helo(props) {
  const { nodes, materials } = useGLTF('/models/helo.gltf')

  const rotor = useRef()

  useFrame((state, delta) => {
    rotor.current.rotation.y += delta * 10
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BackMotor.geometry} material={materials.Metal} position={[-0.14, 1.143, -3.108]} />
      <mesh geometry={nodes.BackWingsContainer.geometry} material={materials.HelicopterBody} position={[-0.195, 1.143, -3.099]} />
      <mesh geometry={nodes.EngineStrut.geometry} material={materials.Metal} position={[0.291, 3.056, -0.352]} />
      <mesh geometry={nodes.GatlingGun.geometry} material={materials.Metal} position={[-17127.322, 0.576, 3020.132]} />
      <mesh geometry={nodes.GlassGasket.geometry} material={materials.WindsheildGasket} position={[0.387, 1.082, 0.2]} />
      <mesh geometry={nodes.GlassGasketTwo.geometry} material={materials['WindsheildGasket.001']} position={[0.442, 1.092, 0.515]} />
      <mesh geometry={nodes.HelicopterBackWings.geometry} material={materials.Metal} position={[-0.225, 1.143, -3.093]} />
      <group position={[0.239, 1.091, -0.636]}>
        <mesh geometry={nodes.Sphere010.geometry} material={materials['HelicopterBody.001']} />
        <mesh geometry={nodes.Sphere010_1.geometry} material={materials.Interior} />
      </group>
      <mesh geometry={nodes.HelicopterBody001.geometry} material={materials.Metal} position={[1110.328, 0.717, -196.12]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.HelicopterBody} position={[-0.215, 1.51, -3.172]} />
      <group position={[0.435, 1.082, 0.478]}>
        <mesh geometry={nodes.Sphere007.geometry} material={materials.Windsheild} />
        <mesh geometry={nodes.Sphere007_1.geometry} material={materials.WindSheildDark} />
      </group>
      <mesh geometry={nodes.StandPlane.geometry} material={materials.Stand} position={[-2183.612, 0.374, 385.463]} />
      <mesh geometry={nodes.TopEngine.geometry} material={materials.HelicopterBody} position={[0.254, 1.733, -0.563]} />
      <mesh ref={rotor} geometry={nodes.TopFin.geometry} material={materials.Metal} position={[0.289, 2.343, -0.354]} rotation={[Math.PI, -0.534, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/models/helo.gltf')
