/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/oil-tank.glb
Author: ittoKubashi7 (https://sketchfab.com/ittoKubashi7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-oil-tank-d8e9ced5cc11428280ffad57f96d8686
Title: Old oil tank
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OilTank(props) {
  const { nodes, materials } = useGLTF('/models/oil-tank.glb')
  return (
    <group {...props} dispose={null} scale={0.015} rotation-y={-2.8}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh   geometry={nodes.Material2.geometry} material={materials.material_5} />
        <mesh  geometry={nodes.Material2_1.geometry} material={materials.material_4} />
        <mesh   geometry={nodes.Material3.geometry} material={materials.material} />
        <mesh  castShadow={true} geometry={nodes.Material3_1.geometry} material={materials.material_7} />
        <mesh   geometry={nodes.Material3_2.geometry} material={materials.material_0} />
        <mesh  castShadow={true} geometry={nodes.Material3_3.geometry} material={materials.material_3} />
        <mesh  geometry={nodes.Material2_2.geometry} material={materials.material_6} />
        <lineSegments geometry={nodes.Material2_3.geometry} material={materials.edge_color000255} />
        <lineSegments geometry={nodes.Material2_4.geometry} material={materials.edge_color1098973255} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/oil-tank.glb')
