/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 public/models/tree.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/models/tree.gltf')
  return (
    <group {...props} dispose={null} scale={[0.125, 0.125, 0.125]}>
      <mesh geometry={nodes['tree-spruce'].geometry} material={materials.color_main} />
    </group>
  )
}

useGLTF.preload('/models/tree.gltf')
